set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256color*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
